name: RaiderCore
version: 2.1
author: Raider
main: org.raider.raidercore.RaiderCore
description: a series of small patches compiled into one file.  Also includes commands to give players leather armor that takes damage like diamond armor.
depend: [SilkSpawners, WorldGuard, WorldEdit,MassiveCore]
commands:
  report:
    description: reports a player to staff for given reason.
    usage: /report (Player) (Reason)
  rsettings:
    description: view the RaiderCore config settings.
    usage: /rsettings
  rconfig:
    description: reload the RaiderCore config.
    usage: /rconfig
  testarmor:
    description: test command for giving players custom leather armor that acts like diamond armor.
    usage: /testarmor <ArmorType>
  rattributes:
    description: check item attributes.
    usage: /rattributes
  xp:
    description: gets an xp bottle.
    usage: /xp <Amount>

